### ISSUE TITLE
Blank Spaces after reloading scripts

### ISSUE THREAD

**Issue by qiangqiang101** [Bob74/iFruitAddon2#1]
After scripts reloaded, it adds new contacts after the old contacts

**Comment by randogaming6252** [comment]
you think you got it bad, its ben 2 years since your post, and ive had the same issue from the moment i start the game. and that alongside the fact that this mod causes massive lag spikes and certain new mods are using this and it hasn't ben updated since 2018.

**Comment by Bob74** [comment]
Didn't see that post actually.

I don't know what could cause this issue but unfortunately I'm not updating this anymore.
I checked the 5 forks of this project, no one seems to have pushed anything on their sides either.
