### ISSUE TITLE
dosent work

### ISSUE THREAD

**Issue by BenDover1525** [Bob74/iFruitAddon2#12]
when i open phone it just shows the original phone of gta v

**Comment by Bob74** [comment]
This is a library intended to be used by mod creators, it won't do anything alone.

**Comment by BenDover1525** [comment]
i use ifruitaddon for 3 mods

**Comment by Bob74** [comment]
Well with that much informations...

What does ScriptHookVDotNet.log says?
Is there any error messages in the console?
Did you check if your GTA folder has writing rights as mentioned here https://github.com/Bob74/iFruitAddon2/issues/3#issuecomment-905921800 and here https://github.com/Bob74/iFruitAddon2/issues/8 ?
