### ISSUE TITLE
not working 

### ISSUE THREAD

**Issue by petar992** [Bob74/iFruitAddon2#13]
i get this in the ifruitaddon2 log:6/26/2023 1:07:33 AM : Creating main directory.
6/26/2023 1:07:54 AM : Creating config file.
6/26/2023 1:08:01 AM : Error: IsUpdateAvailable - Thread was being aborted.
6/26/2023 1:12:00 AM : Error: IsUpdateAvailable - The request was aborted: Could not create SSL/TLS secure channel.
6/26/2023 1:27:12 AM : Error: IsUpdateAvailable - The request was aborted: Could not create SSL/TLS secure channel.
6/26/2023 1:37:50 AM : Error: IsUpdateAvailable - Thread was being aborted.
6/27/2023 3:25:16 PM : Error: IsUpdateAvailable - The request was aborted: Could not create SSL/TLS secure channel.
6/27/2023 3:32:09 PM : Error: IsUpdateAvailable - The request was aborted: Could not create SSL/TLS secure channel.
6/27/2023 10:06:24 PM : Error: IsUpdateAvailable - The request was aborted: Could not create SSL/TLS secure channel.
6/28/2023 1:52:20 PM : Error: IsUpdateAvailable - The request was aborted: Could not create SSL/TLS secure channel.
6/28/2023 2:03:27 PM : Error: IsUpdateAvailable - The request was aborted: Could not create SSL/TLS secure channel.
6/29/2023 4:27:05 PM : Error: IsUpdateAvailable - The request was aborted: Could not create SSL/TLS secure channel.
7/2/2023 2:36:36 PM : Error: IsUpdateAvailable - The request was aborted: Could not create SSL/TLS secure channel.
7/2/2023 2:50:21 PM : Error: IsUpdateAvailable - Thread was being aborted.
7/2/2023 2:54:50 PM : Error: IsUpdateAvailable - The request was aborted: Could not create SSL/TLS secure channel.
7/2/2023 3:00:02 PM : Error: IsUpdateAvailable - The request was aborted: Could not create SSL/TLS secure channel.
7/3/2023 3:51:17 PM : Error: IsUpdateAvailable - The request was aborted: Could not create SSL/TLS secure channel.
7/3/2023 4:07:55 PM : Error: IsUpdateAvailable - The request was aborted: Could not create SSL/TLS secure channel.
7/8/2023 2:20:53 PM : Error: IsUpdateAvailable - The request was aborted: Could not create SSL/TLS secure channel.
7/8/2023 2:51:01 PM : Error: IsUpdateAvailable - The request was aborted: Could not create SSL/TLS secure channel.
7/9/2023 11:40:11 AM : Error: IsUpdateAvailable - The request was aborted: Could not create SSL/TLS secure channel.
7/9/2023 11:57:40 AM : Error: IsUpdateAvailable - The request was aborted: Could not create SSL/TLS secure channel.
7/10/2023 5:02:11 PM : Error: IsUpdateAvailable - The request was aborted: Could not create SSL/TLS secure channel.
7/10/2023 5:07:14 PM : Error: IsUpdateAvailable - The request was aborted: Could not create SSL/TLS secure channel.
7/10/2023 5:20:30 PM : Error: IsUpdateAvailable - The request was aborted: Could not create SSL/TLS secure channel.
7/10/2023 5:26:27 PM : Error: IsUpdateAvailable - The request was aborted: Could not create SSL/TLS secure channel.
7/10/2023 5:33:42 PM : Error: IsUpdateAvailable - The request was aborted: Could not create SSL/TLS secure channel.
7/12/2023 2:53:45 PM : Error: IsUpdateAvailable - The request was aborted: Could not create SSL/TLS secure channel.
7/16/2023 10:11:41 PM : Error: IsUpdateAvailable - The request was aborted: Could not create SSL/TLS secure channel.
7/19/2023 1:28:57 PM : Error: IsUpdateAvailable - The request was aborted: Could not create SSL/TLS secure channel.
7/20/2023 7:21:58 PM : Error: IsUpdateAvailable - The request was aborted: Could not create SSL/TLS secure channel.
7/20/2023 7:28:07 PM : Error: IsUpdateAvailable - The request was aborted: Could not create SSL/TLS secure channel.
7/20/2023 10:35:28 PM : Error: IsUpdateAvailable - Thread was being aborted.
7/20/2023 11:08:16 PM : Error: IsUpdateAvailable - The request was aborted: Could not create SSL/TLS secure channel.
7/21/2023 2:09:47 PM : Error: IsUpdateAvailable - The request was aborted: Could not create SSL/TLS secure channel.
7/21/2023 2:38:18 PM : Error: IsUpdateAvailable - The request was aborted: Could not create SSL/TLS secure channel.
7/21/2023 2:49:10 PM : Error: IsUpdateAvailable - The request was aborted: Could not create SSL/TLS secure channel.
7/21/2023 3:07:18 PM : Error: IsUpdateAvailable - The request was aborted: Could not create SSL/TLS secure channel.
7/21/2023 3:09:50 PM : Error: IsUpdateAvailable - The request was aborted: Could not create SSL/TLS secure channel.
7/21/2023 3:39:27 PM : Error: IsUpdateAvailable - The request was aborted: Could not create SSL/TLS secure channel.
7/21/2023 4:29:25 PM : Error: IsUpdateAvailable - The request was aborted: Could not create SSL/TLS secure channel.
7/21/2023 5:07:59 PM : Error: IsUpdateAvailable - The request was aborted: Could not create SSL/TLS secure channel.
7/21/2023 5:13:03 PM : Error: IsUpdateAvailable - The request was aborted: Could not create SSL/TLS secure channel.
7/21/2023 5:13:30 PM : Error: IsUpdateAvailable - The request was aborted: Could not create SSL/TLS secure channel.
7/21/2023 5:17:55 PM : Error: IsUpdateAvailable - The request was aborted: Could not create SSL/TLS secure channel.
7/21/2023 5:18:17 PM : Error: IsUpdateAvailable - The request was aborted: Could not create SSL/TLS secure channel.
7/21/2023 5:22:30 PM : Error: IsUpdateAvailable - The request was aborted: Could not create SSL/TLS secure channel.
7/22/2023 12:02:15 AM : Error: IsUpdateAvailable - The request was aborted: Could not create SSL/TLS secure channel.
7/22/2023 3:12:25 PM : Error: IsUpdateAvailable - The request was aborted: Could not create SSL/TLS secure channel.
7/22/2023 3:41:51 PM : Error: IsUpdateAvailable - The request was aborted: Could not create SSL/TLS secure channel.
7/23/2023 2:30:12 PM : Error: IsUpdateAvailable - The request was aborted: Could not create SSL/TLS secure channel.
7/23/2023 3:01:19 PM : Error: IsUpdateAvailable - The request was aborted: Could not create SSL/TLS secure channel.
7/23/2023 3:36:07 PM : Error: IsUpdateAvailable - The request was aborted: Could not create SSL/TLS secure channel.
7/24/2023 3:07:59 PM : Error: IsUpdateAvailable - The request was aborted: Could not create SSL/TLS secure channel.
7/24/2023 3:31:56 PM : Error: IsUpdateAvailable - The request was aborted: Could not create SSL/TLS secure channel.
7/24/2023 3:35:39 PM : Error: IsUpdateAvailable - The request was aborted: Could not create SSL/TLS secure channel.
7/24/2023 7:15:40 PM : Error: IsUpdateAvailable - The request was aborted: Could not create SSL/TLS secure channel.
7/24/2023 7:34:19 PM : Error: IsUpdateAvailable - The request was aborted: Could not create SSL/TLS secure channel.
7/24/2023 11:31:05 PM : Error: IsUpdateAvailable - The request was aborted: Could not create SSL/TLS secure channel.
7/25/2023 1:54:02 PM : Error: IsUpdateAvailable - The request was aborted: Could not create SSL/TLS secure channel.
7/25/2023 2:43:31 PM : Error: IsUpdateAvailable - The request was aborted: Could not create SSL/TLS secure channel.
7/25/2023 2:43:39 PM : Error: IsUpdateAvailable - The request was aborted: Could not create SSL/TLS secure channel.
7/25/2023 2:45:50 PM : Error: IsUpdateAvailable - The request was aborted: Could not create SSL/TLS secure channel.
7/25/2023 9:40:57 PM : Error: IsUpdateAvailable - The request was aborted: Could not create SSL/TLS secure channel.
7/25/2023 9:56:47 PM : Error: IsUpdateAvailable - The request was aborted: Could not create SSL/TLS secure channel.
7/26/2023 2:00:39 PM : Error: IsUpdateAvailable - The request was aborted: Could not create SSL/TLS secure channel.
7/27/2023 12:42:10 AM : Error: IsUpdateAvailable - The request was aborted: Could not create SSL/TLS secure channel.
7/27/2023 12:47:20 AM : Error: IsUpdateAvailable - The request was aborted: Could not create SSL/TLS secure channel.
7/27/2023 12:59:26 AM : Error: IsUpdateAvailable - The request was aborted: Could not create SSL/TLS secure channel.
7/27/2023 4:12:55 PM : Error: IsUpdateAvailable - The request was aborted: Could not create SSL/TLS secure channel.
7/27/2023 4:24:44 PM : Error: IsUpdateAvailable - The request was aborted: Could not create SSL/TLS secure channel.
7/27/2023 10:04:52 PM : Error: IsUpdateAvailable - The request was aborted: Could not create SSL/TLS secure channel.
7/28/2023 5:06:19 PM : Error: IsUpdateAvailable - The request was aborted: Could not create SSL/TLS secure channel.
7/28/2023 5:09:49 PM : Error: IsUpdateAvailable - Thread was being aborted.
7/28/2023 5:21:01 PM : Error: IsUpdateAvailable - The request was aborted: Could not create SSL/TLS secure channel.
7/28/2023 5:30:28 PM : Error: IsUpdateAvailable - The request was aborted: Could not create SSL/TLS secure channel.
7/28/2023 6:28:32 PM : Error: IsUpdateAvailable - The request was aborted: Could not create SSL/TLS secure channel.
7/28/2023 6:36:25 PM : Creating main directory.
7/28/2023 6:36:56 PM : Creating config file.
7/28/2023 6:37:01 PM : Error: IsUpdateAvailable - Thread was being aborted.
. And this in the scripthookv log:[18:52:25] [ERROR] Failed to instantiate script Class1 because constructor threw an exception: System.IO.FileNotFoundException: Could not load file or assembly 'System.Runtime, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a' or one of its dependencies. The system cannot find the file specified.
File name: 'System.Runtime, Version=6.0.0.0, Culture=neutral, PublicKeyToken=b03f5f7f11d50a3a'
   at Class1..ctor()

WRN: Assembly binding logging is turned OFF.
To enable assembly bind failure logging, set the registry value [HKLM\Software\Microsoft\Fusion!EnableLog] (DWORD) to 1.
Note: There is some performance penalty associated with assembly bind failure logging.
To turn this feature off, remove the registry value [HKLM\Software\Microsoft\Fusion!EnableLog].
                 And i dont know if the scripthookv log file has to do with this but i got it at the same so so please help

**Comment by petar992** [comment]
and also it worked before but it suddenly it stopped working i didnt install anything else so idk what happend

**Comment by Bob74** [comment]
Are you using iFruitAddon2 version 2.1.0? (https://github.com/Bob74/iFruitAddon2/releases/tag/v2.1.0)
This update issue was supposed to be patched.

If you still have this error, you can disable update check by setting this line to false in the **config.ini** file:
```
CheckForUpdates=false
```

For your error concerning `Class1`, it is not related to iFruitAddon2 (this class doesn't exists in iFruiAddon2). It is another plugin that seems to require .Net 6.
Maybe you uninstalled it from your computer since last time? You can try to install it from Microsoft: https://dotnet.microsoft.com/en-us/download/dotnet/thank-you/runtime-desktop-6.0.20-windows-x64-installer

It doesn't seem to be your case but you should also make sure your GTA V directory is not locked on read-only (RGSC launcher can update your directory and lock it, it happened in the past): https://github.com/Bob74/iFruitAddon2/issues/3#issuecomment-905921800

**Comment by petar992** [comment]
I did disable the check for update theres no error but the contacts dont show up and if your wondering the mod is enable all interiors

**Comment by Bob74** [comment]
If a mod is crashing, it will prevent other mods to load.

The crash comes from EnableAllInteriors, it contains the Class1 file that won't load:
![image](https://github.com/Bob74/iFruitAddon2/assets/9498543/0ae46432-1658-4e3d-8f29-e34c39680cb7)

**Comment by petar992** [comment]
so i just delete it and check if theres an update that fixes this

**Comment by petar992** [comment]
i fixed the mod but now i cant pull up the phone

**Comment by petar992** [comment]
the contacts wont show up again  even tho i installed the mod on a fresh install

**Comment by petar992** [comment]
oh wait nvm i fixed it tnx
