### ISSUE TITLE
ssl/tls aborted, is this mod abandoned?

### ISSUE THREAD

**Issue by randogaming6252** [Bob74/iFruitAddon2#2]
log file is short and is postable.
6/11/2021 10:55:10 PM : Creating config directory.
6/11/2021 10:55:10 PM : Creating config file.
6/11/2021 10:55:10 PM : Error: IsUpdateAvailable - The request was aborted: Could not create SSL/TLS secure channel.
thats the ifruitaddon2 log file

**Comment by Bob74** [comment]
GitHub seems to have aborted HTTP support and I didn't implement HTTPS in the code.
But since I won't update this mod, you can simply disable the update checks from the config file.
You should have a folder named **iFruitAddon2** inside your script folder. In this folder, you will find the file **config.ini** and you need to edit the line:
`CheckForUpdates=true`
to
`CheckForUpdates=false`

You will certainly see performances improvements when starting the game since checking for update fell to time out.

You need to have launched the game at least once with this mod for the config file to appear.

**Comment by randogaming6252** [comment]
[General]
StartIndex=40
thats all thats in there

**Comment by randogaming6252** [comment]
that lines not present, and ive ran the mod thousands of times, well kinds, it timed out every time

**Comment by randogaming6252** [comment]
[config.txt](https://github.com/Bob74/iFruitAddon2/files/6679823/config.txt)

**Comment by randogaming6252** [comment]
aside from being renamed so i can post it, its the config.ini file

**Comment by randogaming6252** [comment]
side question, is this the modders mod throwing the exception or is it the ifruitaddon2?

[21:16:28] [INFO] Started script WorkingJuggernautSuit.Class1.
[21:16:46] [ERROR] Caught fatal unhandled exception:
System.MissingMethodException: Method not found: 'Void iFruitAddon2.CustomiFruit.Close(Int32)'.
   at WorkingJuggernautSuit.Class1.loadMenu(iFruitContact contact)
   at iFruitAddon2.iFruitContact.OnAnswered(iFruitContact sender)
   at iFruitAddon2.iFruitContact.Update()
   at iFruitAddon2.iFruitContactCollection.Update(Int32 handle)
   at iFruitAddon2.CustomiFruit.Update()
   at WorkingJuggernautSuit.Class1.OnTick(Object sender, EventArgs e)
   at SHVDN.Script.MainLoop()
[21:16:46] [ERROR] The exception was thrown while executing the script WorkingJuggernautSuit.Class1.
[21:16:46] [WARNING] Aborted script WorkingJuggernautSuit.Class1.

**Comment by Bob74** [comment]
I think you might not have the latest version of iFruitAddon2 (**2.1.0**).
Github messed up with the releases and was showing 2.0.0 as the latest, I fixed it.

Updating and adding `CheckForUpdates=false` to your `config.ini` should do the trick.

For **WorkingJuggernautSuit**, it is the mod that throws the error and if you use an outdated version of iFruitAddon2, this is completely normal. Try again after updating :)

**Comment by randogaming6252** [comment]
mod author sent me a copy of his ifruitaddon2. the version is the correct one, issue is resolved, wish idve known about the version issue. wouldve saved me a lot of trouble from the get-go

**Comment by Bob74** [comment]
Well, whenever you need to download something, take it from the official source and download the latest version, simple as that.
The latest version was listed in the releases, if you had a looked at the releases you'd have seen it.
