### ISSUE TITLE
It's not working

### ISSUE THREAD

**Issue by TownFan49** [Bob74/iFruitAddon2#4]
The new contacts don't appear, i have 2 mods that use this one and both don't appear in my contacts and it doesn't expands the contacts list. I have ScriptHookVDotNet and Script Hook V, still with the file on scripts it doesnt work

**Comment by Bob74** [comment]
Please post the log files or the console output so we can see what the issue is.

**Comment by TownFan49** [comment]
[ScriptHookVDotNet.log](https://github.com/Bob74/iFruitAddon2/files/7558903/ScriptHookVDotNet.log)
i think its this one the log

**Comment by Bob74** [comment]
All right, I think I figured what's going on.

You lack the correct versions of [LemonUI](https://fr.gta5-mods.com/tools/lemonui).
You did install `LemonUI` for **FiveM** but not for **ScriptHookVDotNet** (those are two very different things actually)

The log file tells you it cannot load your mods :
`LemonUI.FiveM.net.dll: System.IO.FileNotFoundException: No se puede cargar el archivo o ensamblado 'CitizenFX.Core.Client`

I would suggest you to: 
- first, remove `LemonUI.FiveM.net.dll` from your scripts folder
- then install both `LemonUI.SHVDN2.dll` and `LemonUI.SHVDN3.dll` from the `LemonUI` mod archive (it is weird to install both but that's the author recommendations from the pinned post [here](https://fr.gta5-mods.com/tools/lemonui#description_tab))

Tell me if that helped, and if not, paste your current `ScriptHookVDotNet.log` file 🙂

**Comment by TownFan49** [comment]
idk how i did it, but i managed it to work, but this helped. Thanks :)
