### ISSUE TITLE
Crashes when i load into game.

### ISSUE THREAD

**Issue by That1GuyDel** [Bob74/iFruitAddon2#8]
Im trying to use this mod with "Little Jacob Contact" which needs IFruitAddon2 but whenever I load into game IFruitAddon2 crashes on me giving this error.: System.io.filenotfoundexception. I have no idea why it does this and help would be much appreciated. I'm using the latest ScriptHookV ScriptHookV.Net and every other needed file but just have trouble with this one. (IFruitAddon2)

**Comment by Bob74** [comment]
It might have issue with creating the log file, ensure that you have writing rights on GTA V folder and subfolders with your user (see https://github.com/Bob74/iFruitAddon2/issues/3#issuecomment-905921800)

**Comment by That1GuyDel** [comment]
> It might have issue with creating the log file, ensure that you have writing rights on GTA V folder and subfolders with your user (see [#3 (comment)](https://github.com/Bob74/iFruitAddon2/issues/3#issuecomment-905921800))

It worked thank you so much! Took away my permissions a few times in the process on accident lol but i got it to work. Thanks.

**Comment by Bob74** [comment]
No problem, glad it worked: )
